[package]
authors = ["IdanArye <idanarye@gmail.com>"]
name = "ghost-text-file"
version = "0.1.0"

[dependencies]
env_logger = "0.4.3"
hyper = "0.10.6"
log = "0.3.8"
serde = "1.0.17"
serde_derive = "1.0.18"
serde_json = "1.0.5"
tempdir = "0.3.5"
websocket = "0.20.2"
